import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :koikoi, KoikoiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dQdIKDz7yyokfu60kyIEKTDhbf6ciiYvhCi5Dq80eH6Q82hYRaiGVRHHzznkT+oP",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# MongoDB configuration (Windows host via WSL2 gateway)
config :koikoi, Koikoi.Repo,
  url: "mongodb://#{System.get_env("MONGODB_HOST", "172.29.208.1")}:27017/koikoi_dev",
  pool_size: 10

# Stripe dev configuration
config :koikoi, :stripe,
  webhook_secret: System.get_env("STRIPE_WEBHOOK_SECRET") || "whsec_placeholder",
  basic_price_id: System.get_env("STRIPE_BASIC_PRICE_ID") || "price_basic_placeholder",
  vip_price_id: System.get_env("STRIPE_VIP_PRICE_ID") || "price_vip_placeholder"

# Enable dev routes for dashboard and mailbox
config :koikoi, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
